# Generated by Django 4.2.7 on 2023-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_product_taxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxe',
            field=models.FloatField(choices=[(0.055, '0.55%'), (0.1, '10%'), (0.2, '20%')], default=0.2),
        ),
    ]
